name: Build PyInstaller App

on:
  push:
    branches:
      - main   # This triggers the build when changes are pushed to the 'main' branch
  pull_request:
    branches:
      - main
  workflow_dispatch:   # Allows manual trigger of the workflow

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.7

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt

      - name: Find package data files (CSV)
        run: |
          python -c "import os, ramanbiolib; print(os.path.join(os.path.dirname(ramanbiolib.__file__), 'db'))" > data_directory.txt

      - name: Add binary and data files to PyInstaller
        run: |
          DATA_DIR=$(cat data_directory.txt)  # Read the directory from the file
          pyinstaller --add-data "$DATA_DIR/*.csv:ramanbiolib/db" src/app.py  # Use the correct path

      - name: Build the application using PyInstaller
        run: |
          pyinstaller -y app.spec --clean  # Build your application with PyInstaller

      - name: Upload the executable as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: ramanbiolib-ui-ubuntu
          path: dist/app