name: Build PyInstaller App

on:
  push:
    branches:
      - main  # Trigger build when changes are pushed to 'main'
  pull_request:
    branches:
      - main
  workflow_dispatch:   # Allow manual trigger of the workflow

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest]  # Build for both Windows and macOS

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Force Intel (x86_64) architecture
        if: runner.os == 'macOS'
        run: |
          export RUNNER_ARCH=x86_64  # Force Intel architecture

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.7

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt

      - name: Install Visual C++ Redistributable (Windows)
        if: runner.os == 'Windows'
        run: |
          choco install vcredist2010 -y
        shell: powershell

      - name: Build the application using PyInstaller (Windows)
        if: runner.os == 'Windows'
        run: |
          pyinstaller -y app_win.spec --clean

      - name: Build the application using PyInstaller (macOS)
        if: runner.os == 'macOS'
        run: |
          pyinstaller -y app_macos.spec --clean

      - name: List generated files
        run: |
          ls -R dist/
        shell: bash

      - name: Upload the executable as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: ramanbiolib-ui-${{ runner.os }}
          path: |
            dist/ramanbiolib-ui/
            dist/ramanbiolib-ui.app/